// <auto-generated />
using System;
using MagicVilla_villaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_villaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_villaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 19, 10, 34, 40, 777, DateTimeKind.Local).AddTicks(1215),
                            Details = "Royal Villa provides beachfront accommodations in Trabzon. This villa offers free private parking and a shared kitchen.",
                            ImageUrl = "https://limestays.com/wp-content/uploads/2023/01/34-926x618.jpg",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 19, 10, 34, 40, 777, DateTimeKind.Local).AddTicks(1271),
                            Details = "Explore your family getaway with our premium pool villa, featuring a spacious room with two king-sized beds and a private pool right in your room.",
                            ImageUrl = "https://image-tc.galaxy.tf/wijpeg-vh7o2qzd9xv299ah5v1vav87/grand-lexis-port-dickson-premium-pool-villa-3-thumbnail-w4896_wide.jpg?crop=0%2C105%2C2000%2C1125&width=1140",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 19, 10, 34, 40, 777, DateTimeKind.Local).AddTicks(1274),
                            Details = "Featuring a garden, Highend Private Pool Villa features accommodations in Amphoe Koh Samui. This beachfront property offers access to a balcony.",
                            ImageUrl = "https://www.luva-villas.com/img/news_11_crop_0_1671810979.webp",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Rate = 400.0,
                            Sqft = 750,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 19, 10, 34, 40, 777, DateTimeKind.Local).AddTicks(1277),
                            Details = "Diamond Villa has view of islands and the Aegean Sea, with private pool. The villa offers accommodation with butler service, maximized luxury and advantages.",
                            ImageUrl = "https://static.wixstatic.com/media/b32baf_ff2d9aeb3aff4cb99694364312052495~mv2.jpg/v1/fill/w_640,h_426,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/b32baf_ff2d9aeb3aff4cb99694364312052495~mv2.jpg",
                            Name = "Diamond Villa",
                            Occupancy = 4,
                            Rate = 550.0,
                            Sqft = 900,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 19, 10, 34, 40, 777, DateTimeKind.Local).AddTicks(1280),
                            Details = "Providing an outdoor swimming pool, Diamond Pool Villa@Samui provides accommodations in Koh Samui. This chalet features free private parking, free shuttle.",
                            ImageUrl = "https://cdn-5d68e683f911c80950255463.closte.com/wp-content/uploads/2019/05/Edit_Overview_Villa-2.jpg",
                            Name = "Diamond Pool Villa",
                            Occupancy = 4,
                            Rate = 600.0,
                            Sqft = 1100,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
